/**
 * India district (ADM2) gazetteer.
 *
 * Two payloads back this module, and the split matters:
 *
 *   - `india_districts_index.json` (~69 KB) carries name, parent state,
 *     centroid and bounding box for all 734 districts and no geometry. The
 *     search box and the district list need nothing else, so typeahead is
 *     usable long before any polygon has been parsed.
 *   - `india_districts.geojson` (~1.3 MB) carries the simplified rings. It is
 *     fetched lazily, only once something actually needs to draw or hit-test a
 *     boundary.
 *
 * Both are generated by `scripts/build_districts.py` from geoBoundaries gbOpen
 * IND ADM2 (2021). Property keys are single letters to keep the payload small:
 * `d` district, `s` state, `c` centroid.
 */

export interface District {
  /** District name, e.g. "Kancheepuram". */
  name: string;
  /** Parent state or union territory, e.g. "Tamil Nadu". */
  state: string;
  /** Representative point, [lon, lat] — centroid of the largest ring. */
  centroid: [number, number];
  /** [minLon, minLat, maxLon, maxLat]. */
  bbox: [number, number, number, number];
  /** Stable identity: `state/name`, slugified. Safe as a React key. */
  id: string;
}

export interface DistrictGeometry extends District {
  /**
   * Outer rings only, as [lon, lat] pairs. Holes are dropped: they exist in
   * the source for a handful of enclave districts, and carrying them would
   * complicate hit-testing for a result no camera altitude here can resolve.
   */
  rings: number[][][];
}

// -----------------------------------------------------------------------------
// Identity & normalisation
// -----------------------------------------------------------------------------

export const districtId = (name: string, state: string): string =>
  `${state}/${name}`.toLowerCase().replace(/[^a-z0-9/]+/g, '-');

/**
 * Fold a name to a comparable form.
 *
 * Indian district names are transliterations and reach users in many spellings
 * — "Kanchipuram"/"Kancheepuram", "Bengaluru Urban"/"Bangalore Urban". Casing,
 * accents and punctuation are stripped so none of those differences block a
 * match; the genuinely different spellings are handled by the alias table and
 * the subsequence pass in `searchDistricts`.
 */
export const normalise = (s: string): string =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

/**
 * Common names that do not share a prefix or substring with the official
 * spelling in the boundary file, so no amount of fuzzy matching would find
 * them. Keys are what a user types; values are the official name.
 */
const ALIASES: Record<string, string> = {
  bombay: 'Mumbai',
  madras: 'Chennai',
  calcutta: 'Kolkata',
  bangalore: 'Bangalore',
  bengaluru: 'Bangalore',
  mysore: 'Mysore',
  poona: 'Pune',
  trivandrum: 'Thiruvananthapuram',
  cochin: 'Ernakulam',
  kochi: 'Ernakulam',
  baroda: 'Vadodara',
  gurgaon: 'Gurgaon',
  gurugram: 'Gurgaon',
  pondicherry: 'Puducherry',
  allahabad: 'Allahabad',
  prayagraj: 'Allahabad',
  simla: 'Shimla',
  ooty: 'Nilgiris',
  vizag: 'Visakhapatnam',
  ncr: 'New Delhi',
};

// -----------------------------------------------------------------------------
// Loading
// -----------------------------------------------------------------------------

interface RawIndexEntry {
  d: string;
  s: string;
  c: [number, number];
  b: [number, number, number, number];
}

let indexPromise: Promise<District[]> | null = null;
let geometryPromise: Promise<DistrictGeometry[]> | null = null;

/** All 734 districts without geometry. Cached for the life of the page. */
export function loadDistrictIndex(): Promise<District[]> {
  if (!indexPromise) {
    indexPromise = fetch('/geo/india_districts_index.json')
      .then((r) => {
        if (!r.ok) throw new Error(`district index ${r.status}`);
        return r.json();
      })
      .then((raw: { districts: RawIndexEntry[] }) =>
        raw.districts.map((e) => ({
          name: e.d,
          state: e.s,
          centroid: e.c,
          bbox: e.b,
          id: districtId(e.d, e.s),
        })),
      )
      .catch((err) => {
        // Do not cache a rejection: a transient failure would otherwise
        // permanently disable district search for the rest of the session.
        indexPromise = null;
        throw err;
      });
  }
  return indexPromise;
}

/** District boundary rings. ~1.3 MB — fetched only when first needed. */
export function loadDistrictGeometry(): Promise<DistrictGeometry[]> {
  if (!geometryPromise) {
    geometryPromise = fetch('/geo/india_districts.geojson')
      .then((r) => {
        if (!r.ok) throw new Error(`district geometry ${r.status}`);
        return r.json();
      })
      .then((fc: { features: GeoFeature[] }) => fc.features.map(toGeometry))
      .catch((err) => {
        geometryPromise = null;
        throw err;
      });
  }
  return geometryPromise;
}

interface GeoFeature {
  properties: { d: string; s: string; c: [number, number] };
  geometry:
    | { type: 'Polygon'; coordinates: number[][][] }
    | { type: 'MultiPolygon'; coordinates: number[][][][] };
}

function toGeometry(f: GeoFeature): DistrictGeometry {
  const polys =
    f.geometry.type === 'Polygon'
      ? [f.geometry.coordinates]
      : f.geometry.coordinates;
  const rings = polys.map((p) => p[0]).filter((r) => r && r.length > 3);

  let minLon = Infinity;
  let minLat = Infinity;
  let maxLon = -Infinity;
  let maxLat = -Infinity;
  for (const ring of rings) {
    for (const [lon, lat] of ring) {
      if (lon < minLon) minLon = lon;
      if (lat < minLat) minLat = lat;
      if (lon > maxLon) maxLon = lon;
      if (lat > maxLat) maxLat = lat;
    }
  }

  return {
    name: f.properties.d,
    state: f.properties.s,
    centroid: f.properties.c,
    bbox: [minLon, minLat, maxLon, maxLat],
    id: districtId(f.properties.d, f.properties.s),
    rings,
  };
}

// -----------------------------------------------------------------------------
// Search
// -----------------------------------------------------------------------------

export interface DistrictMatch {
  district: District;
  score: number;
  /** Character positions in `district.name` that matched, for highlighting. */
  hits: number[];
}

/**
 * Rank districts against a typed query.
 *
 * Scoring is tiered rather than a single similarity metric, because the tiers
 * are what make the list feel predictable: an exact name always outranks a
 * prefix, which always outranks an interior substring, which always outranks a
 * loose subsequence. Ties break on the shorter name, so "Bijapur" beats
 * "Bijapur (Karnataka)" when both match equally.
 */
export function searchDistricts(
  districts: District[],
  query: string,
  limit = 12,
): DistrictMatch[] {
  const q = normalise(query);
  if (!q) return [];

  const aliased = ALIASES[q];
  const results: DistrictMatch[] = [];

  for (const district of districts) {
    const name = normalise(district.name);
    const state = normalise(district.state);

    let score = 0;
    let hits: number[] = [];

    if (aliased && district.name === aliased) {
      score = 1200;
    } else if (name === q) {
      score = 1000;
    } else if (name.startsWith(q)) {
      score = 800 - name.length;
      hits = range(0, q.length);
    } else if (wordStarts(name).some((i) => name.startsWith(q, i))) {
      const i = wordStarts(name).find((j) => name.startsWith(q, j))!;
      score = 600 - name.length;
      hits = range(i, i + q.length);
    } else if (name.includes(q)) {
      const i = name.indexOf(q);
      score = 400 - name.length;
      hits = range(i, i + q.length);
    } else if (state === q || state.startsWith(q)) {
      // The query names a state: surface its districts, alphabetically.
      score = 300 - district.name.length * 0.01;
    } else if (state.includes(q)) {
      score = 200 - district.name.length * 0.01;
    } else {
      const sub = subsequence(name, q);
      if (sub) {
        score = 100 - sub.spread;
        hits = sub.hits;
      }
    }

    if (score > 0) results.push({ district, score, hits });
  }

  results.sort(
    (a, b) => b.score - a.score || a.district.name.localeCompare(b.district.name),
  );
  return results.slice(0, limit);
}

const range = (a: number, b: number) =>
  Array.from({ length: b - a }, (_, i) => a + i);

function wordStarts(s: string): number[] {
  const out: number[] = [];
  for (let i = 1; i < s.length; i++) if (s[i - 1] === ' ') out.push(i);
  return out;
}

/**
 * In-order character match, tolerating gaps — catches "knchpram" for
 * "kancheepuram". `spread` is how far apart the matches landed, so tight
 * matches rank above scattered ones.
 */
function subsequence(
  haystack: string,
  needle: string,
): { hits: number[]; spread: number } | null {
  const hits: number[] = [];
  let h = 0;
  for (const ch of needle) {
    const found = haystack.indexOf(ch, h);
    if (found === -1) return null;
    hits.push(found);
    h = found + 1;
  }
  return { hits, spread: hits[hits.length - 1] - hits[0] - needle.length + 1 };
}

// -----------------------------------------------------------------------------
// Spatial lookup
// -----------------------------------------------------------------------------

const GRID_CELL_DEG = 0.5;
const GRID_ORIGIN_LON = 66;
const GRID_ORIGIN_LAT = 5;

/**
 * Uniform-grid index over the districts.
 *
 * Clicking the globe has to answer "which of 734 polygons is this?" inside a
 * pointer event. Testing every polygon means ~70,000 ray-cast segments per
 * click; bucketing bounding boxes into half-degree cells brings the candidate
 * set down to single digits, and the exact point-in-polygon test then runs
 * only on those.
 */
export class DistrictLocator {
  private cells = new Map<number, number[]>();

  constructor(private districts: DistrictGeometry[]) {
    districts.forEach((d, i) => {
      const [minLon, minLat, maxLon, maxLat] = d.bbox;
      for (let x = this.cellX(minLon); x <= this.cellX(maxLon); x++) {
        for (let y = this.cellY(minLat); y <= this.cellY(maxLat); y++) {
          const key = this.key(x, y);
          const bucket = this.cells.get(key);
          if (bucket) bucket.push(i);
          else this.cells.set(key, [i]);
        }
      }
    });
  }

  private cellX = (lon: number) => Math.floor((lon - GRID_ORIGIN_LON) / GRID_CELL_DEG);
  private cellY = (lat: number) => Math.floor((lat - GRID_ORIGIN_LAT) / GRID_CELL_DEG);
  private key = (x: number, y: number) => x * 4096 + y;

  /** The district containing this point, or null if it is outside India. */
  locate(lon: number, lat: number): DistrictGeometry | null {
    const bucket = this.cells.get(this.key(this.cellX(lon), this.cellY(lat)));
    if (!bucket) return null;

    for (const i of bucket) {
      const d = this.districts[i];
      const [minLon, minLat, maxLon, maxLat] = d.bbox;
      if (lon < minLon || lon > maxLon || lat < minLat || lat > maxLat) continue;
      if (d.rings.some((ring) => pointInRing(lon, lat, ring))) return d;
    }
    return null;
  }

  /**
   * Districts whose bounding box intersects the given window. Used to decide
   * which districts are worth labelling or fetching weather for.
   */
  within(
    minLon: number,
    minLat: number,
    maxLon: number,
    maxLat: number,
  ): DistrictGeometry[] {
    return this.districts.filter((d) => {
      const [a, b, c, e] = d.bbox;
      return !(c < minLon || a > maxLon || e < minLat || b > maxLat);
    });
  }
}

/** Ray-casting point-in-polygon. */
export function pointInRing(lon: number, lat: number, ring: number[][]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

/** Great-circle distance in km. */
export function haversineKm(
  aLat: number,
  aLon: number,
  bLat: number,
  bLon: number,
): number {
  const R = 6371;
  const dLat = ((bLat - aLat) * Math.PI) / 180;
  const dLon = ((bLon - aLon) * Math.PI) / 180;
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((aLat * Math.PI) / 180) *
      Math.cos((bLat * Math.PI) / 180) *
      Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
